@startuml ITJobs - Secuencia: Login con JWT

skinparam sequenceMessageAlign center

actor "Usuario" as U
participant "AuthController\n<<REST>>" as CTRL
participant "LoginUseCase\n<<Use Case>>" as UC
participant "LoadUserPort\n<<Out Port>>" as LOAD
participant "CredentialsVerifier\n<<Domain Service>>" as VER
participant "PasswordEncoderPort\n<<Out Port>>" as ENC
participant "TokenGeneratorPort\n<<Out Port>>" as TOKEN

U -> CTRL : POST /api/v1/auth/login\n{email, password}
activate CTRL

CTRL -> CTRL : Map DTO → LoginCommand

CTRL -> UC : execute(command)
activate UC

' Cargar usuario
UC -> LOAD : findByEmail(email)
activate LOAD
LOAD --> UC : UserAggregate
deactivate LOAD

' Verificar credenciales
UC -> VER : verifyCredentials(user, rawPassword, encoder)
activate VER

VER -> ENC : matches(rawPassword, user.password.value())
activate ENC
ENC --> VER : true
deactivate ENC

VER --> UC : void (credenciales válidas)
deactivate VER

' Generar tokens
UC -> TOKEN : generateAccessToken(userId, roles)
activate TOKEN
TOKEN --> UC : "eyJhbG..."
deactivate TOKEN

UC -> TOKEN : generateRefreshToken(userId)
activate TOKEN
TOKEN --> UC : "eyJhbG..."
deactivate TOKEN

' Preparar respuesta
UC -> UC : Map → AuthTokenResponse
UC --> CTRL : AuthTokenResponse
deactivate UC

CTRL -> CTRL : Map → AuthResponse
CTRL --> U : 200 OK\n{accessToken, refreshToken}
deactivate CTRL

@enduml
