package com.ITJobsBackend.authentication.domain.valueobjects;

import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.UUID;

import com.ITJobsBackend.shared.domain.exceptions.ValidationException;

/**
 * Value object representing a one-time password-reset token.
 *
 * <p>Generated by {@code ForgotPasswordUseCase} and published inside a
 * {@code PasswordResetRequestedEvent} so that the email infrastructure can deliver it to the
 * user. The token is valid for {@value #EXPIRY_HOURS} hour(s) from generation.
 *
 * <p>Invariants:
 * <ul>
 *   <li>Token value must not be blank</li>
 *   <li>Expiration must not be null</li>
 * </ul>
 */
public record PasswordResetToken(String value, Instant expiresAt) {

  private static final long EXPIRY_HOURS = 1;

  public PasswordResetToken {
    if (value == null || value.isBlank()) {
      throw new ValidationException("Reset token cannot be blank");
    }
    if (expiresAt == null) {
      throw new ValidationException("Reset token expiration cannot be null");
    }
  }

  /**
   * Generates a new random token that expires in {@value #EXPIRY_HOURS} hour(s).
   *
   * @return a freshly generated {@code PasswordResetToken}
   */
  public static PasswordResetToken generate() {
    return new PasswordResetToken(
        UUID.randomUUID().toString(), Instant.now().plus(EXPIRY_HOURS, ChronoUnit.HOURS));
  }

  /**
   * Reconstructs an existing token from persistence.
   *
   * @param value     the stored token string
   * @param expiresAt the stored expiration instant
   * @return a {@code PasswordResetToken} wrapping the provided values
   */
  public static PasswordResetToken of(String value, Instant expiresAt) {
    return new PasswordResetToken(value, expiresAt);
  }

  /**
   * Checks whether the provided string matches this token.
   *
   * @param provided the token submitted by the user
   * @return {@code true} if the strings match
   */
  public boolean matches(String provided) {
    return value.equals(provided);
  }

  /**
   * @return {@code true} if the current UTC instant is past {@link #expiresAt()}
   */
  public boolean isExpired() {
    return Instant.now().isAfter(expiresAt);
  }

  @Override
  public String toString() {
    return "PasswordResetToken{value='[PROTECTED]', expiresAt=" + expiresAt + "}";
  }
}
